### ISSUE TITLE
Consider Renaming to Ember-Pop-Over

### ISSUE THREAD

**Issue by pzuraq** [paddle8/ember-popup-menu#9]
This component is much more like the pop-over or tool-tip components from bootstrap than it is a dropdown, particularly in the way that the components work. They aren't limited to being activated by the containing or nearby element, which allows them to work on span's of inline text, for instance.

I had difficulty finding this plugin, despite it being exactly what I was looking for. I think it would be better for users looking for this functionality if the name were changed. For backwards compatibility, we could keep this repository open and archive it so current users would still have access.

**Comment by tim-evans** [comment]
@pzuraq that makes a lot of sense. I never really felt great about the name anyways.

With this, things would change to:

```handlebars
{{#pop-over}}
  Hiiiiiiiiiii
{{/pop-over}}
```

**Comment by pzuraq** [comment]
Yep! Seems to match the functionality a lot more, +discoverability.

**Comment by tim-evans** [comment]
See https://github.com/tim-evans/ember-pop-over for a WIP in updating the addon

**Comment by pzuraq** [comment]
@tim-evans Looks solid! Can you publish to npm? I'd really like to define the flows in `flow.js` :)

**Comment by tim-evans** [comment]
I'll do my best. I'd like to make sure that integration with liquid-fire works well before cutting a release.

**Comment by pzuraq** [comment]
Mmk, anything I can do to help?

**Comment by tim-evans** [comment]
I'd like the flows file to be created via a blueprint. That way you can manage all flows for your application.

**Comment by tim-evans** [comment]
Okie dokey! I've published ember-pop-over. It generates a flows file per project. That way, you have full control over flows named in your app.
